DROP ALL OBJECTS;

CREATE TABLE IF NOT EXISTS users (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL PRIMARY KEY,
    name    VARCHAR(255)                              NOT NULL,
    email   VARCHAR(512)                              NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY    NOT NULL PRIMARY KEY,
    name            VARCHAR(255)                               NOT NULL UNIQUE,
    description     VARCHAR(255)                               NOT NULL,
    is_available    BOOLEAN                                    NOT NULL,
    owner_id        BIGINT REFERENCES users(id)                NOT NULL
);