
CREATE TABLE IF NOT EXISTS users (
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY   NOT NULL PRIMARY KEY,
    name    VARCHAR(255)                              NOT NULL,
    email   VARCHAR(512)                              NOT NULL UNIQUE
);

CREATE TABLE IF NOT EXISTS items (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY    NOT NULL PRIMARY KEY,
    name            VARCHAR(255)                               NOT NULL UNIQUE,
    description     VARCHAR(255)                               NOT NULL,
    is_available    BOOLEAN                                    NOT NULL,
    owner_id        BIGINT REFERENCES users(id)                NOT NULL
);

CREATE TABLE IF NOT EXISTS bookings (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL PRIMARY KEY,
    start_date      TIMESTAMP                                       NOT NULL,
    end_date        TIMESTAMP                                       NOT NULL,
    item_id         BIGINT REFERENCES items(id) ON DELETE CASCADE   NOT NULL,
    booker_id       BIGINT REFERENCES users(id) ON DELETE CASCADE   NOT NULL,
    status          VARCHAR(255)                                    NOT NULL
);

CREATE TABLE IF NOT EXISTS comments (
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY         NOT NULL PRIMARY KEY,
    item_id         BIGINT REFERENCES items(id) ON DELETE CASCADE   NOT NULL,
    user_id         BIGINT REFERENCES users(id) ON DELETE CASCADE   NOT NULL,
    text            VARCHAR(255)                                    NOT NULL,
    created_date    TIMESTAMP                                       NOT NULL
);